name: locker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.3+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  get: ^4.6.1
  pin_code_fields: ^7.3.0
  page_transition: ^2.0.4
  http: ^0.13.4
  shared_preferences: ^2.0.13
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/common/logo.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/common/
    - assets/login/